/**
 * ROOM-CONFIG.JS
 * ===============
 * Shared room configuration module for Cherry Tree Centre
 * Loads room config from Firebase and generates dynamic CSS
 * 
 * Usage: Include after Firebase init, call loadRoomConfig() before loading bookings
 * <script src="js/room-config.js"></script>
 */

(function() {
  'use strict';
  console.log('🏠 room-config.js loading...');

  // ================================
  // DEFAULT ROOM CONFIGURATION
  // Fallback if Firebase unavailable
  // ================================
  const defaultRoomConfig = {
    'Room_1': { enabled: true, color: '#d4a5a5', borderColor: '#b89090', displayName: 'Room 1', order: 1 },
    'Room_2': { enabled: true, color: '#b299d4', borderColor: '#9680c0', displayName: 'Room 2', order: 2 },
    'Room_4': { enabled: true, color: '#a5d4a5', borderColor: '#90b890', displayName: 'Room 4', order: 3 },
    'Room_5': { enabled: true, color: '#e57373', borderColor: '#d32f2f', displayName: 'Room 5', order: 4 },
    'Room_6': { enabled: true, color: '#c8a882', borderColor: '#b5946e', displayName: 'Room 6', order: 5 },
    'Room_7': { enabled: true, color: '#e6d45a', borderColor: '#d4c347', displayName: 'Room 7', order: 6 },
    'Room_8': { enabled: true, color: '#80cbc4', borderColor: '#4db6ac', displayName: 'Room 8', order: 7 },
    'Room_9': { enabled: true, color: '#ce93d8', borderColor: '#ba68c8', displayName: 'Room 9', order: 8 },
    'Car_Park': { enabled: true, color: '#90caf9', borderColor: '#42a5f5', displayName: 'Car Park', order: 9 },
    'Online': { enabled: true, color: '#7dd87d', borderColor: '#6bc46b', displayName: 'Online', order: 10 }
  };

  // ================================
  // STATE (exposed globally)
  // ================================
  window.roomConfig = {};
  window.enabledRooms = [];

  // ================================
  // LOAD ROOM CONFIG FROM FIREBASE
  // ================================
  window.loadRoomConfig = async function() {
    console.log('🏠 Loading room configuration from Firebase...');
    
    try {
      // Check if Firebase database is available
      if (typeof database === 'undefined') {
        console.warn('⚠️ Firebase database not available, using defaults');
        window.roomConfig = JSON.parse(JSON.stringify(defaultRoomConfig));
      } else {
        const snapshot = await database.ref('room_config').once('value');
        const config = snapshot.val();
        
        if (config && Object.keys(config).length > 0) {
          window.roomConfig = config;
          console.log('✅ Loaded room config from Firebase');
        } else {
          window.roomConfig = JSON.parse(JSON.stringify(defaultRoomConfig));
          console.log('ℹ️ No Firebase config found, using defaults');
        }
      }
      
      // Build enabled rooms array sorted by order
      window.enabledRooms = Object.entries(window.roomConfig)
        .filter(([key, room]) => room.enabled)
        .sort((a, b) => (a[1].order || 99) - (b[1].order || 99))
        .map(([key, room]) => ({ key, ...room }));
      
      console.log(`🏠 ${window.enabledRooms.length} enabled rooms loaded`);
      
      // Generate dynamic CSS for room colours
      generateRoomStyles();
      
      return window.roomConfig;
      
    } catch (error) {
      console.error('❌ Error loading room config:', error);
      window.roomConfig = JSON.parse(JSON.stringify(defaultRoomConfig));
      window.enabledRooms = Object.entries(defaultRoomConfig)
        .filter(([key, room]) => room.enabled)
        .sort((a, b) => (a[1].order || 99) - (b[1].order || 99))
        .map(([key, room]) => ({ key, ...room }));
      
      generateRoomStyles();
      return window.roomConfig;
    }
  };

  // ================================
  // GENERATE DYNAMIC CSS
  // Same approach as admin pages
  // ================================
  function generateRoomStyles() {
    // Remove existing dynamic styles if present
    let styleEl = document.getElementById('room-dynamic-styles');
    if (!styleEl) {
      styleEl = document.createElement('style');
      styleEl.id = 'room-dynamic-styles';
      document.head.appendChild(styleEl);
    }
    
    let css = '/* Dynamic room colours - generated by room-config.js */\n';
    
    window.enabledRooms.forEach(room => {
      const className = room.key.toLowerCase().replace('_', '-');
      
      // Grid cell styles for booked cells (day view)
      css += `.grid-cell.booked.${className} { background: ${room.color}; border-left: 4px solid ${room.borderColor}; }\n`;
      
      // Booking segment styles (for multi-booking cells in week view)
      css += `.booking-segment.${className} { background: ${room.color}; border-left: 3px solid ${room.borderColor}; }\n`;
      
      // Legend colour styles
      css += `.legend-color.${className} { background: ${room.color}; border-color: ${room.borderColor}; }\n`;
    });
    
    // Special styling for car park (slightly transparent)
    css += `.grid-cell.booked.car-park { opacity: 0.85; }\n`;
    css += `.booking-segment.car-park { opacity: 0.85; }\n`;
    
    styleEl.textContent = css;
    console.log('🎨 Dynamic room styles generated');
  }

  // ================================
  // ROOM MAPPING FUNCTIONS
  // ================================

  /**
   * Get room key from booking data
   * Handles various room formats in the database
   */
  window.getRoomKey = function(booking) {
    if (!booking) return null;
    
    const room = booking.room;
    
    // Check location for online bookings
    if (booking.location && booking.location.toLowerCase().includes('online')) {
      return 'Online';
    }
    
    if (!room) return null;
    
    // Direct match with config keys
    if (window.roomConfig[room]) return room;
    
    // Handle various formats
    if (room === '1' || room === 'Room_1' || room === 'Room 1') return 'Room_1';
    if (room === '2' || room === 'Room_2' || room === 'Room 2') return 'Room_2';
    if (room === '4' || room === 'Room_4' || room === 'Room 4') return 'Room_4';
    if (room === '5' || room === 'Room_5' || room === 'Room 5') return 'Room_5';
    if (room === '6' || room === 'Room_6' || room === 'Room 6') return 'Room_6';
    if (room === '7' || room === 'Room_7' || room === 'Room 7') return 'Room_7';
    if (room === '8' || room === 'Room_8' || room === 'Room 8') return 'Room_8';
    if (room === '9' || room === 'Room_9' || room === 'Room 9') return 'Room_9';
    if (room === 'Car Park' || room === 'Car_Park' || room.toLowerCase() === 'car park') return 'Car_Park';
    if (room === 'Online' || room === 'online') return 'Online';
    
    return null;
  };

  /**
   * Get room mapping (roomNumber and roomClass) from booking
   * Used for cell styling and identification
   */
  window.getRoomMapping = function(booking) {
    const roomKey = window.getRoomKey(booking);
    
    if (!roomKey) {
      return { roomNumber: null, roomClass: '' };
    }
    
    const roomClass = roomKey.toLowerCase().replace('_', '-');
    
    // Room number for cell ID generation
    let roomNumber = null;
    if (roomKey === 'Room_1') roomNumber = '1';
    else if (roomKey === 'Room_2') roomNumber = '2';
    else if (roomKey === 'Room_4') roomNumber = '4';
    else if (roomKey === 'Room_5') roomNumber = '5';
    else if (roomKey === 'Room_6') roomNumber = '6';
    else if (roomKey === 'Room_7') roomNumber = '7';
    else if (roomKey === 'Room_8') roomNumber = '8';
    else if (roomKey === 'Room_9') roomNumber = '9';
    else if (roomKey === 'Car_Park') roomNumber = 'car-park';
    else if (roomKey === 'Online') roomNumber = 'online';
    
    return { roomNumber, roomClass };
  };

  /**
   * Get display name for a room from booking
   */
  window.getRoomDisplayName = function(booking) {
    const roomKey = window.getRoomKey(booking);
    
    if (!roomKey) {
      return booking?.room || 'Unknown';
    }
    
    // Get from config if available
    if (window.roomConfig[roomKey] && window.roomConfig[roomKey].displayName) {
      return window.roomConfig[roomKey].displayName;
    }
    
    // Fallback: convert key to display name
    return roomKey.replace('_', ' ');
  };

  /**
   * Get room colour from config
   */
  window.getRoomColor = function(roomKey) {
    if (window.roomConfig[roomKey]) {
      return {
        color: window.roomConfig[roomKey].color,
        borderColor: window.roomConfig[roomKey].borderColor
      };
    }
    
    // Fallback
    if (defaultRoomConfig[roomKey]) {
      return {
        color: defaultRoomConfig[roomKey].color,
        borderColor: defaultRoomConfig[roomKey].borderColor
      };
    }
    
    return { color: '#e0e0e0', borderColor: '#ccc' };
  };

  console.log('✅ room-config.js loaded - call loadRoomConfig() after Firebase init');
})();
